<html>
    <head>
    <title>nopaste</title>

        <?php $this->assets->outputCss(); ?>
    </head>
    <h2>
        Sign up using this form
    </h2>

    <?php echo $this->tag->form("index/register");?>

    <p>
        <label for="text">
            input text
            </label>
    <?php echo $this->tag->textField("text");?>
    </p>

    <p>
    <?php echo $this->tag->submitButton("Register");?>
    </p>
    </form>
</html>
